In [1]:
from roboflow import Roboflow
rf = Roboflow(api_key="rK7UN9J72kBKdKI0bzDh")
project = rf.workspace("newton-zdy8s").project("remy-fb4aw")
version = project.version(1)
dataset = version.download("yolov8")

loading Roboflow workspace...
loading Roboflow project...

### Preprocessando os dados do conjunto de datasets baixado do roboflow
limitanod o numero de imagens por classe

In [9]:
import os
labels_path = "REMY-1/train/labels"
ds_l = os.listdir("REMY-1/train/labels")
max = 446
para_eliminar = []

label_pra_freq = {}
for i in range(10):
    label_pra_freq[str(i)]=0


for l in ds_l:
    deletar_esta_label = False
    for linha in open(f"{labels_path}/{l}", 'r', encoding='utf-8').readlines():
        classe = linha[0]
        label_pra_freq[classe] +=1
        if(label_pra_freq[classe]>max):
            deletar_esta_label=True
    if(deletar_esta_label):
        para_eliminar.append(l)


label_pra_freq = {}
for i in range(10):
    label_pra_freq[str(i)]=0

for l in ds_l:
    if l in para_eliminar:
        continue
    else:
        for linha in open(f"{labels_path}/{l}", 'r', encoding='utf-8').readlines():
            classe = linha[0]
            label_pra_freq[classe] +=1

print("frequencia de cada classe limitando apenas a frequencia a 446")
print(label_pra_freq)

para_eliminar = []

cont_vid =0
for l in ds_l:
    if l[:3]=="VID":
        if cont_vid>100:
            para_eliminar.append(l)
        else:
            cont_vid+=1


label_pra_freq = {}
for i in range(10):
    label_pra_freq[str(i)]=0

for l in ds_l:
    deletar_esta_label = False
    for linha in open(f"{labels_path}/{l}", 'r', encoding='utf-8').readlines():
        classe = linha[0]
        label_pra_freq[classe] +=1
        if(label_pra_freq[classe]>max):
            deletar_esta_label=True
    if(deletar_esta_label):
        para_eliminar.append(l)

label_pra_freq = {}
for i in range(10):
    label_pra_freq[str(i)]=0

for l in ds_l:
    if l in para_eliminar:
        continue
    else:
        for linha in open(f"{labels_path}/{l}", 'r', encoding='utf-8').readlines():
            classe = linha[0]
            label_pra_freq[classe] +=1


print("frequencia de cada classe limitando a frequencia dos videos a 100 e depois a freq a 446 ")
print(label_pra_freq)

frequencia de cada classe limitando apenas a frequencia a 446
{'0': 446, '1': 444, '2': 351, '3': 0, '4': 0, '5': 433, '6': 258, '7': 384, '8': 360, '9': 180}
frequencia de cada classe limitando a frequencia dos videos a 100 e depois a freq a 446
{'0': 446, '1': 444, '2': 351, '3': 0, '4': 0, '5': 433, '6': 258, '7': 384, '8': 360, '9': 179}

In [10]:
#vou tirar as imagens de video tmb
images_path = "REMY-1/train/images"
para_eliminar_corrigido = []

for l in para_eliminar:
    nome_base = os.path.splitext(l)[0]
    image_path = os.path.join(images_path, f"{nome_base}.jpg")
    label_path = os.path.join(labels_path, l)

    if os.path.exists(image_path) and os.path.exists(label_path):
        para_eliminar_corrigido.append(l)

for l in para_eliminar_corrigido:
    nome_base = os.path.splitext(l)[0]
    image_path = os.path.join(images_path, f"{nome_base}.jpg")
    label_path = os.path.join(labels_path, l)
    
    os.remove(image_path)
    os.remove(label_path)

Fundindo a classe 4 (SmallFork) com a classe 2 (Fork) e a classe 5 (SmallSpoon) com a classe 6 (Spoon)

In [11]:
ds_l = os.listdir("REMY-1/train/labels")
for l in ds_l:
    modificou = False
    old_rows = []
    new_rows = []
    with open(f"{labels_path}/{l}", 'r', encoding='utf-8') as arq:
        for r in arq.readlines():
            old_rows.append(r)

            if (r[0]=='3'):
                modificou=True
                r = '1'+ r[1:]
            elif(r[0]=='4'):
                modificou=True
                r = '5'+ r[1:]

            new_rows.append(r)
    if(modificou):
        with open(f"{labels_path}/{l}", 'w') as arq:
            arq.writelines(new_rows)
        print("antigas")
        for r in old_rows:
            print(r)

        print("novas")
        with open(f"{labels_path}/{l}", 'r', encoding='utf-8') as arq:
            for r in arq.readlines():
                print(r)

In [1]:
import ultralytics
model = ultralytics.YOLO('yolov8n.pt')
model.train(
    data='REMY-1/data.yaml',
    epochs=50,
    imgsz=640,
    val=False,
    batch=16,
    name='treinada (falta bandeja)(classes fundidas)(dataset feito por mim)',  # Nome para a pasta de resultados
    hsv_h=0.03,      # Hue augmentation
    hsv_s=0.6,       # Saturation augmentation  
    hsv_v=0.5,       # Value augmentation
    translate=0.2,   # Translation augmentation
    scale=0.9,       # Scale augmentation
    fliplr=0.5,      # Horizontal flip
    mosaic=1.0,      # Mosaic augmentation
    mixup=0.15       # Mixup augmentation
)

New https://pypi.org/project/ultralytics/8.3.204 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.178 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2050, 3902MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=REMY-1/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.03, hsv_s=0.6, hsv_v=0.5, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.15, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=treinada (falta bandeja)(classes fundidas)(dataset feito por mim), nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/treinada (falta bandeja)(classes fundidas)(dataset feito por mim), save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.9, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.2, val=False, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    432817  ultralytics.nn.modules.head.Detect           [11, [64, 128, 256]]
YOLO11n summary: 181 layers, 2,591,985 parameters, 2,591,969 gradients, 6.5 GFLOPs

Transferred 448/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 604.6±233.8 MB/s, size: 242.9 KB)

train: Scanning /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/labels.cache... 2328 images, 478 backgrounds, 0 corrupt: 100%|██████████| 2328/2328 [00:00<?, ?it/s]

train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/0235c3bc-20250924_164029.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/08320284-20250924_164539.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/0f68bdb7-20250924_164343.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/14ffa2c3-20250924_164130.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/160a535f-20250924_164446.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/192e5b61-20250924_164658.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/204ebe81-20250924_164356.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/2221a841-20250924_164701.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/23d0e155-20250924_164133.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/321963f3-20250924_164504.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/34bdccc3-20250924_164418.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/42710d6f-20250924_164631.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/45d62e06-20250924_164106.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/4d22ab8f-20250924_164425.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/4f913ade-20250924_164434.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/55f196b1-20250924_164623.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/5c3dfe07-20250924_164548.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/61cc5ef9-20250924_164637.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/682bbf78-20250924_164430.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/68ab1c88-20250924_164633.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/69ce0c3e-20250924_164048.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/6a86dfaa-20250924_164448.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/6b449eba-20250924_164415.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/71d337b0-20250924_164351.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/74127e41-20250924_164359.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/781eb2b8-20250924_164509.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/785b4a66-20250924_164438.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/7cc62eb3-20250924_164050.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/7e78ad1f-20250924_164404.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/828e3fb3-20250924_164339.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/88d45eed-20250924_164340.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/8be4bc5d-20250924_164139.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/931d20d3-20250924_164129.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/9502f726-20250924_164146.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/9ca4d1f5-20250924_164401.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/a1cc6128-20250924_164536.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/a6daf052-20250924_164045.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/aaf2f6a9-20250924_164529.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/bd9de2d5-20250924_164042.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/cdbb0819-20250924_164522.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/cf0cfa82-20250924_164442.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/d12af80f-20250924_164104.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/da711dcb-20250924_164538.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/de1728fc-20250924_164640.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/faa988db-20250924_164628.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/fc8b26c8-20250924_164420.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/fd3fd6f5-20250924_164642.jpg: corrupt JPEG restored and saved
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 618, len(boxes) = 2951. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.

/home/pc/venvs/data_science/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 449.7±232.5 MB/s, size: 245.6 KB)

val: Scanning /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/labels.cache... 2328 images, 478 backgrounds, 0 corrupt: 100%|██████████| 2328/2328 [00:00<?, ?it/s]

train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/0235c3bc-20250924_164029.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/08320284-20250924_164539.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/0f68bdb7-20250924_164343.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/14ffa2c3-20250924_164130.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/160a535f-20250924_164446.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/192e5b61-20250924_164658.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/204ebe81-20250924_164356.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/2221a841-20250924_164701.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/23d0e155-20250924_164133.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/321963f3-20250924_164504.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/34bdccc3-20250924_164418.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/42710d6f-20250924_164631.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/45d62e06-20250924_164106.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/4d22ab8f-20250924_164425.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/4f913ade-20250924_164434.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/55f196b1-20250924_164623.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/5c3dfe07-20250924_164548.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/61cc5ef9-20250924_164637.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/682bbf78-20250924_164430.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/68ab1c88-20250924_164633.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/69ce0c3e-20250924_164048.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/6a86dfaa-20250924_164448.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/6b449eba-20250924_164415.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/71d337b0-20250924_164351.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/74127e41-20250924_164359.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/781eb2b8-20250924_164509.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/785b4a66-20250924_164438.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/7cc62eb3-20250924_164050.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/7e78ad1f-20250924_164404.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/828e3fb3-20250924_164339.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/88d45eed-20250924_164340.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/8be4bc5d-20250924_164139.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/931d20d3-20250924_164129.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/9502f726-20250924_164146.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/9ca4d1f5-20250924_164401.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/a1cc6128-20250924_164536.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/a6daf052-20250924_164045.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/aaf2f6a9-20250924_164529.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/bd9de2d5-20250924_164042.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/cdbb0819-20250924_164522.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/cf0cfa82-20250924_164442.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/d12af80f-20250924_164104.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/da711dcb-20250924_164538.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/de1728fc-20250924_164640.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/faa988db-20250924_164628.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/fc8b26c8-20250924_164420.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/REMY-1/train/images/fd3fd6f5-20250924_164642.jpg: corrupt JPEG restored and saved
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 618, len(boxes) = 2951. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.

Plotting labels to runs/detect/treinada (falta bandeja)(classes fundidas)(dataset feito por mim)/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000667, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/treinada (falta bandeja)(classes fundidas)(dataset feito por mim)
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/50       2.2G      1.155      3.629      1.285         36        640: 100%|██████████| 146/146 [00:37<00:00,  3.94it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/50      2.24G      1.241      2.605      1.323         35        640: 100%|██████████| 146/146 [00:35<00:00,  4.09it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/50      2.23G      1.247      2.246      1.314         37        640: 100%|██████████| 146/146 [00:35<00:00,  4.11it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/50      2.24G      1.197      1.973        1.3         23        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/50      2.23G      1.174      1.854      1.283         12        640: 100%|██████████| 146/146 [00:35<00:00,  4.14it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/50      2.23G      1.148      1.726      1.268         26        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/50      2.24G       1.13      1.605      1.259         36        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/50      2.23G      1.117       1.51      1.244         29        640: 100%|██████████| 146/146 [00:35<00:00,  4.14it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/50      2.24G      1.097      1.417      1.241         31        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/50      2.24G      1.075      1.364      1.227         33        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/50      2.24G      1.037      1.286        1.2         21        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/50      2.23G      1.041      1.259      1.192         27        640: 100%|██████████| 146/146 [00:35<00:00,  4.11it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/50      2.24G       1.02      1.221      1.182         17        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/50      2.24G      1.022      1.196      1.187         16        640: 100%|██████████| 146/146 [00:35<00:00,  4.10it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/50      2.23G     0.9872      1.156      1.175         43        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/50      2.22G     0.9917       1.14      1.159         18        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/50      2.23G     0.9893        1.1      1.164         14        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/50      2.23G     0.9721      1.101      1.157         26        640: 100%|██████████| 146/146 [00:35<00:00,  4.12it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/50      2.25G     0.9888      1.079       1.16         15        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/50      2.23G     0.9748      1.071      1.156         25        640: 100%|██████████| 146/146 [00:35<00:00,  4.12it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/50      2.24G      0.961      1.059      1.145         33        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/50      2.23G     0.9369      1.005      1.136         18        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/50      2.24G     0.9613      1.001      1.145         26        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/50      2.23G     0.9207     0.9753      1.125         26        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/50      2.24G     0.9238     0.9596      1.124         37        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/50      2.24G     0.9235     0.9646      1.128         21        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/50      2.24G     0.8997     0.9149      1.107         38        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/50      2.23G     0.9025     0.9198      1.113         25        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/50      2.24G     0.8784     0.8773      1.095         22        640: 100%|██████████| 146/146 [00:35<00:00,  4.14it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/50      2.24G     0.8678     0.8735        1.1         12        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/50      2.25G     0.9029      0.916      1.114         11        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/50      2.23G     0.8789     0.8671      1.101         27        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      33/50      2.24G     0.8741     0.8536      1.094         31        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      34/50      2.24G     0.8487     0.8246      1.084         38        640: 100%|██████████| 146/146 [00:35<00:00,  4.14it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      35/50      2.24G     0.8498     0.8384       1.08         22        640: 100%|██████████| 146/146 [00:35<00:00,  4.13it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      36/50      2.24G     0.8343     0.8126       1.07         44        640: 100%|██████████| 146/146 [00:35<00:00,  4.14it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      37/50      2.26G      0.831     0.8037      1.077         22        640: 100%|██████████| 146/146 [00:35<00:00,  4.14it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      38/50      2.23G     0.8345     0.7968      1.078         30        640: 100%|██████████| 146/146 [00:35<00:00,  4.12it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      39/50      2.25G     0.8307     0.7818      1.067         42        640: 100%|██████████| 146/146 [00:35<00:00,  4.12it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      40/50      2.24G     0.8302     0.7865      1.066         27        640: 100%|██████████| 146/146 [00:35<00:00,  4.12it/s]

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      41/50      2.23G     0.6561     0.5552      1.025          9        640: 100%|██████████| 146/146 [00:35<00:00,  4.11it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      42/50      2.22G     0.6334     0.5164     0.9961          9        640: 100%|██████████| 146/146 [00:35<00:00,  4.17it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      43/50      2.23G     0.6244     0.4999     0.9949          9        640: 100%|██████████| 146/146 [00:35<00:00,  4.16it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      44/50      2.21G     0.6211     0.5027     0.9999          8        640: 100%|██████████| 146/146 [00:35<00:00,  4.15it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      45/50      2.23G      0.608     0.4868     0.9939          7        640: 100%|██████████| 146/146 [00:35<00:00,  4.16it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      46/50      2.22G     0.6061     0.4671     0.9892          9        640: 100%|██████████| 146/146 [00:35<00:00,  4.16it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      47/50      2.23G     0.5944     0.4513     0.9647         13        640: 100%|██████████| 146/146 [00:35<00:00,  4.14it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      48/50      2.22G     0.5833     0.4448      0.972          4        640: 100%|██████████| 146/146 [00:35<00:00,  4.16it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      49/50      2.23G     0.5808     0.4446      0.971         12        640: 100%|██████████| 146/146 [00:34<00:00,  4.18it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      50/50      2.22G     0.5848     0.4403     0.9759          7        640: 100%|██████████| 146/146 [00:34<00:00,  4.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 73/73 [00:12<00:00,  6.05it/s]

                   all       2328       2951       0.88      0.914      0.917      0.818

50 epochs completed in 0.499 hours.
Optimizer stripped from runs/detect/treinada (falta bandeja)(classes fundidas)(dataset feito por mim)/weights/last.pt, 5.5MB
Optimizer stripped from runs/detect/treinada (falta bandeja)(classes fundidas)(dataset feito por mim)/weights/best.pt, 5.5MB

Validating runs/detect/treinada (falta bandeja)(classes fundidas)(dataset feito por mim)/weights/best.pt...
Ultralytics 8.3.178 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2050, 3902MiB)
YOLO11n summary (fused): 100 layers, 2,584,297 parameters, 0 gradients, 6.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 73/73 [00:09<00:00,  7.36it/s]

                   all       2328       2951      0.879      0.914      0.917      0.818
   SacolaTipoEcobagSla        303        473      0.859      0.996      0.992      0.862
                  Fork        253        444      0.894      0.995      0.994       0.86
                 Knife        248        351      0.921      0.997      0.995      0.862
                 Spoon        329        433      0.905      0.993      0.995      0.886
                  bowl        192        258      0.961          1      0.995      0.973
                 gauze        297        384      0.937      0.987      0.994      0.915
                 plate        312        360      0.984          1      0.995      0.961
                 trash        222        236      0.838      0.992      0.993      0.803
                  copo          5         12      0.613      0.267      0.302      0.238
Speed: 0.2ms preprocess, 2.8ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to runs/detect/treinada (falta bandeja)(classes fundidas)(dataset feito por mim)

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([ 0,  1,  2,  5,  6,  7,  8,  9, 10])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7ec164360790>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,      0.4535,      0.4535,           0],
       [          1,           1,           1, ...,     0.83774,     0.83774,           0],
       [          1,           1,           1, ...,     0.87313,     0.87313,           0],
       ...,
       [          1,           1,           1, ...,           1,           1,           0],
       [          1,           1,           1, ...,    0.046809,    0.023405,           0],
       [          1,           1,           1, ...,  0.00013712,  6.8562e-05,           0]]), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

# OPEN IMAGES V7 DATASET

In [28]:

# Define the classes you want to download
classes = ["Spoon", "Fork", "Kitchen knife", "Kitchen utensil", "Kitchenware", "Knife", "Mixing bowl", "Bowl", "Coffee cup",  "Measuring cup", "Serving tray", 
           "Serving tray", "Plastic bag", "Handbag", "Wine glass", "Mug","Beaker","Plate"]

In [ ]:
import fiftyone as fo
import fiftyone.zoo as foz


# Load the dataset with specific classes
dataset = foz.load_zoo_dataset( 
    "open-images-v7",
    split="train",  # or "validation" or "test"
    label_types=["detections"],  # bounding boxes
    classes=classes,
    max_samples=4000,  # adjust based on your needs, or remove for all samples
    dataset_name="open-images-custom",
)

Downloading split 'train' to '/home/pc/fiftyone/open-images-v7/train' if necessary
Downloading 'https://storage.googleapis.com/openimages/2018_04/train/train-images-boxable-with-rotation.csv' to '/home/pc/fiftyone/open-images-v7/train/metadata/image_ids.csv'
 100% |██████|    4.8Gb/4.8Gb [23.1s elapsed, 0s remaining, 209.0Mb/s]
Downloading 'https://storage.googleapis.com/openimages/v5/class-descriptions-boxable.csv' to '/home/pc/fiftyone/open-images-v7/train/metadata/classes.csv'
Downloading 'https://storage.googleapis.com/openimages/2018_04/bbox_labels_600_hierarchy.json' to '/tmp/tmp7fifq9se/metadata/hierarchy.json'
Downloading 'https://storage.googleapis.com/openimages/v6/oidv6-train-annotations-bbox.csv' to '/home/pc/fiftyone/open-images-v7/train/labels/detections.csv'
Downloading 4000 images
 100% |█████████████████| 4000/4000 [2.8m elapsed, 0s remaining, 14.1 files/s]
Dataset info written to '/home/pc/fiftyone/open-images-v7/info.json'
You are running the oldest supported major version of MongoDB. Please refer to https://deprecation.voxel51.com for deprecation notices. You can suppress this exception by setting your `database_validation` config parameter to `False`. See https://docs.voxel51.com/user_guide/config.html#configuring-a-mongodb-connection for more information
Loading existing dataset 'open-images-custom'. To reload from disk, either delete the existing dataset or provide a custom `dataset_name` to use

## Não rodar, eu tive que manualemente mudar o nome de algumas classes do json

In [ ]:
import os
import pandas as pd
import json
import yaml
from tqdm import tqdm

# --- CONFIGURAÇÃO ---
# O script assume a seguinte estrutura de pastas:
# ./converter_dataset.py
# ./dataset/
#      info.json
#      train/
#          data/
#              <imagens>.jpg
#          labels/
#              detections.csv

# Caminhos de entrada (geralmente não precisam de alteração se a estrutura acima for seguida)
BASE_DIR = 'open-images-v7'
INFO_JSON_PATH = os.path.join(BASE_DIR, 'info.json')
IMAGES_DIR = os.path.join(BASE_DIR, 'train/data')
CSV_PATH = os.path.join(BASE_DIR, 'train/detections.csv')

# Caminhos de saída
OUTPUT_DIR = 'yolo_dataset' # Pasta onde o novo dataset será criado
LABELS_OUTPUT_DIR = os.path.join(OUTPUT_DIR, 'labels')
YAML_OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'dataset.yaml')

# --- LÓGICA DO SCRIPT ---

def create_yolo_dataset():
    """
    Converte um dataset no formato Open Images (baixado com FiftyOne)
    para o formato YOLOv8.
    """
    print("Iniciando a conversão do dataset para o formato YOLO...")

    # 1. Criar diretórios de saída
    print(f"Criando diretório de saída em: '{OUTPUT_DIR}'")
    os.makedirs(LABELS_OUTPUT_DIR, exist_ok=True)

    # 2. Carregar informações de classes do info.json
    try:
        with open(INFO_JSON_PATH, 'r') as f:
            info_data = json.load(f)
        class_names = info_data.get('classes', [])
        if not class_names:
            print(f"AVISO: A chave 'classes' não foi encontrada em '{INFO_JSON_PATH}'. Verifique o arquivo.")
            return
        class_to_id = {name: i for i, name in enumerate(class_names)}
        print(f"Sucesso! {len(class_names)} classes encontradas.")
    except FileNotFoundError:
        print(f"ERRO: Arquivo 'info.json' não encontrado em '{INFO_JSON_PATH}'. Verifique o caminho.")
        return

    # 3. Carregar e filtrar o CSV de anotações
    try:
        df = pd.read_csv(CSV_PATH)
        print(f"Total de anotações no CSV: {len(df)}")
    except FileNotFoundError:
        print(f"ERRO: Arquivo 'detections.csv' não encontrado em '{CSV_PATH}'. Verifique o caminho.")
        return

    # Garantir que estamos processando apenas imagens que realmente existem
    print("Filtrando anotações para imagens existentes na pasta 'data/'...")
    image_filenames_in_dir = set(os.listdir(IMAGES_DIR))
    image_ids_in_dir = {os.path.splitext(f)[0] for f in image_filenames_in_dir}
    
    original_rows = len(df)
    df_filtered = df[df['ImageID'].isin(image_ids_in_dir)].copy()
    print(f"Anotações retidas após filtro: {len(df_filtered)} (de {original_rows})")

    # Mapear nome do arquivo da imagem para seu ID (sem extensão)
    filename_to_id_map = {os.path.splitext(f)[0]: f for f in image_filenames_in_dir}
    df_filtered['ImageFilename'] = df_filtered['ImageID'].map(filename_to_id_map)

    # 4. Processar anotações e criar arquivos .txt
    print("Gerando arquivos de anotação .txt para cada imagem...")
    grouped = df_filtered.groupby('ImageID')
    
    for image_id, group in tqdm(grouped, desc="Processando imagens"):
        txt_filename = f"{image_id}.txt"
        txt_filepath = os.path.join(LABELS_OUTPUT_DIR, txt_filename)
        
        yolo_annotations = []
        for _, row in group.iterrows():
            class_name = row['LabelName']
            if class_name not in class_to_id:
                continue

            class_id = class_to_id[class_name]
            
            # Coordenadas do OpenImages CSV já são normalizadas (0.0 a 1.0)
            x_min, x_max, y_min, y_max = row['XMin'], row['XMax'], row['YMin'], row['YMax']
            
            # Converter para o formato YOLO (center_x, center_y, width, height)
            x_center = (x_min + x_max) / 2.0
            y_center = (y_min + y_max) / 2.0
            width = x_max - x_min
            height = y_max - y_min
            
            yolo_annotations.append(f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}")
            
        if yolo_annotations:
            with open(txt_filepath, 'w') as f:
                f.write('\n'.join(yolo_annotations))

    print(f"Total de {len(grouped)} arquivos .txt criados em '{LABELS_OUTPUT_DIR}'.")

    # 5. Criar o arquivo dataset.yaml
    print(f"Criando o arquivo de configuração '{YAML_OUTPUT_PATH}'...")
    
    # O caminho para as imagens deve ser relativo ao local do arquivo .yaml
    train_images_path = os.path.relpath(IMAGES_DIR, start=OUTPUT_DIR)
    
    yaml_data = {
        'path': os.path.abspath(OUTPUT_DIR), # Ultralytics recomenda um path absoluto
        'train': os.path.relpath(IMAGES_DIR, start=OUTPUT_DIR), # path/to/images
        'val': os.path.relpath(IMAGES_DIR, start=OUTPUT_DIR),  # Usando o mesmo para validação
        'nc': len(class_names),
        'names': class_names
    }
    
    with open(YAML_OUTPUT_PATH, 'w') as f:
        yaml.dump(yaml_data, f, sort_keys=False, default_flow_style=False)

    
        
    print("\n✅ Conversão concluída com sucesso!")
    print("\nEstrutura gerada:")
    print(f"  - {OUTPUT_DIR}/")
    print(f"    - labels/       (Contém os arquivos .txt de anotação)")
    print(f"    - dataset.yaml  (Seu arquivo de configuração)")
    print("\nPróximos passos:")
    print(f"  Para treinar seu modelo, use o comando:")
    print(f"  yolo train data={YAML_OUTPUT_PATH} model=yolov8n.pt epochs=100 imgsz=640")


if __name__ == '__main__':
    create_yolo_dataset()

Iniciando a conversão do dataset para o formato YOLO...
Criando diretório de saída em: 'yolo_dataset'
Sucesso! 601 classes encontradas.
Total de anotações no CSV: 14610229
Filtrando anotações para imagens existentes na pasta 'data/'...
Anotações retidas após filtro: 6293 (de 14610229)
Gerando arquivos de anotação .txt para cada imagem...

Processando imagens: 100%|██████████| 1000/1000 [00:00<00:00, 5641.08it/s]

Total de 1000 arquivos .txt criados em 'yolo_dataset/labels'.
Criando o arquivo de configuração 'yolo_dataset/dataset.yaml'...

✅ Conversão concluída com sucesso!

Estrutura gerada:
  - yolo_dataset/
    - labels/       (Contém os arquivos .txt de anotação)
    - dataset.yaml  (Seu arquivo de configuração)

Próximos passos:
  Para treinar seu modelo, use o comando:
  yolo train data=yolo_dataset/dataset.yaml model=yolov8n.pt epochs=100 imgsz=640

In [17]:
import yaml
import json
from pathlib import Path

dataset_yaml = Path("open-images-v7/dataset.yaml")

with dataset_yaml.open("r", encoding="utf-8") as f:
    data = yaml.safe_load(f)

names = data.get("names", [])
# mapeamento label -> índice (0-based)
label_to_idx = {name: idx for idx, name in enumerate(names)}

print(label_to_idx)

# opcional: salvar como JSON
out = dataset_yaml.parent / "label_to_idx.json"
with out.open("w", encoding="utf-8") as f:
    json.dump(label_to_idx, f, ensure_ascii=False, indent=2)

{'Accordion': 0, 'Adhesive tape': 1, 'Aircraft': 2, 'Airplane': 3, 'Alarm clock': 4, 'Alpaca': 5, 'Ambulance': 6, 'Animal': 7, 'Ant': 8, 'Antelope': 9, 'Apple': 10, 'Armadillo': 11, 'Artichoke': 12, 'Auto part': 13, 'Axe': 14, 'Backpack': 15, 'Bagel': 16, 'Baked goods': 17, 'Balance beam': 18, 'Ball': 19, 'Balloon': 20, 'Banana': 21, 'Band-aid': 22, 'Banjo': 23, 'Barge': 24, 'Barrel': 25, 'Baseball bat': 26, 'Baseball glove': 27, 'Bat (Animal)': 28, 'Bathroom accessory': 29, 'Bathroom cabinet': 30, 'Bathtub': 31, 'Beaker': 32, 'Bear': 33, 'Bed': 34, 'Bee': 35, 'Beehive': 36, 'Beer': 37, 'Beetle': 38, 'Bell pepper': 39, 'Belt': 40, 'Bench': 41, 'Bicycle': 42, 'Bicycle helmet': 43, 'Bicycle wheel': 44, 'Bidet': 45, 'Billboard': 46, 'Billiard table': 47, 'Binoculars': 48, 'Bird': 49, 'Blender': 50, 'Blue jay': 51, 'Boat': 52, 'Bomb': 53, 'Book': 54, 'Bookcase': 55, 'Boot': 56, 'Bottle': 57, 'Bottle opener': 58, 'Bow and arrow': 59, 'Bowl': 60, 'Bowling equipment': 61, 'Box': 62, 'Boy': 63, 'Brassiere': 64, 'Bread': 65, 'Briefcase': 66, 'Broccoli': 67, 'Bronze sculpture': 68, 'Brown bear': 69, 'Building': 70, 'Bull': 71, 'Burrito': 72, 'Bus': 73, 'Bust': 74, 'Butterfly': 75, 'Cabbage': 76, 'Cabinetry': 77, 'Cake': 78, 'Cake stand': 79, 'Calculator': 80, 'Camel': 81, 'Camera': 82, 'Can opener': 83, 'Canary': 84, 'Candle': 85, 'Candy': 86, 'Cannon': 87, 'Canoe': 88, 'Cantaloupe': 89, 'Car': 90, 'Carnivore': 91, 'Carrot': 92, 'Cart': 93, 'Cassette deck': 94, 'Castle': 95, 'Cat': 96, 'Cat furniture': 97, 'Caterpillar': 98, 'Cattle': 99, 'Ceiling fan': 100, 'Cello': 101, 'Centipede': 102, 'Chainsaw': 103, 'Chair': 104, 'Cheese': 105, 'Cheetah': 106, 'Chest of drawers': 107, 'Chicken': 108, 'Chime': 109, 'Chisel': 110, 'Chopsticks': 111, 'Christmas tree': 112, 'Clock': 113, 'Closet': 114, 'Clothing': 115, 'Coat': 116, 'Cocktail': 117, 'Cocktail shaker': 118, 'Coconut': 119, 'Coffee (drink)': 120, 'Coffee cup': 121, 'Coffee table': 122, 'Coffeemaker': 123, 'Coin': 124, 'Common fig': 125, 'Common sunflower': 126, 'Computer keyboard': 127, 'Computer monitor': 128, 'Computer mouse': 129, 'Container': 130, 'Convenience store': 131, 'Cookie': 132, 'Cooking spray': 133, 'Corded phone': 134, 'Cosmetics': 135, 'Couch': 136, 'Countertop': 137, 'Cowboy hat': 138, 'Crab': 139, 'Cream': 140, 'Cricket ball': 141, 'Crocodile': 142, 'Croissant': 143, 'Crown': 144, 'Crutch': 145, 'Cucumber': 146, 'Cupboard': 147, 'Curtain': 148, 'Cutting board': 149, 'Dagger': 150, 'Dairy Product': 151, 'Deer': 152, 'Desk': 153, 'Dessert': 154, 'Diaper': 155, 'Dice': 156, 'Digital clock': 157, 'Dinosaur': 158, 'Dishwasher': 159, 'Dog': 160, 'Dog bed': 161, 'Doll': 162, 'Dolphin': 163, 'Door': 164, 'Door handle': 165, 'Doughnut': 166, 'Dragonfly': 167, 'Drawer': 168, 'Dress': 169, 'Drill (Tool)': 170, 'Drink': 171, 'Drinking straw': 172, 'Drum': 173, 'Duck': 174, 'Dumbbell': 175, 'Eagle': 176, 'Earring': 177, 'Egg': 178, 'Elephant': 179, 'Envelope': 180, 'Eraser': 181, 'Face powder': 182, 'Facial tissue holder': 183, 'Falcon': 184, 'Fashion accessory': 185, 'Fast food': 186, 'Fax': 187, 'Fedora': 188, 'Filing cabinet': 189, 'Fire hydrant': 190, 'Fireplace': 191, 'Fish': 192, 'Flag': 193, 'Flashlight': 194, 'Flower': 195, 'Flowerpot': 196, 'Flute': 197, 'Flying disc': 198, 'Food': 199, 'Food processor': 200, 'Football': 201, 'Football helmet': 202, 'Footwear': 203, 'Fork': 204, 'Fountain': 205, 'Fox': 206, 'French fries': 207, 'French horn': 208, 'Frog': 209, 'Fruit': 210, 'Frying pan': 211, 'Furniture': 212, 'Garden Asparagus': 213, 'Gas stove': 214, 'Giraffe': 215, 'Girl': 216, 'Glasses': 217, 'Glove': 218, 'Goat': 219, 'Goggles': 220, 'Goldfish': 221, 'Golf ball': 222, 'Golf cart': 223, 'Gondola': 224, 'Goose': 225, 'Grape': 226, 'Grapefruit': 227, 'Grinder': 228, 'Guacamole': 229, 'Guitar': 230, 'Hair dryer': 231, 'Hair spray': 232, 'Hamburger': 233, 'Hammer': 234, 'Hamster': 235, 'Hand dryer': 236, 'Handbag': 237, 'Handgun': 238, 'Harbor seal': 239, 'Harmonica': 240, 'Harp': 241, 'Harpsichord': 242, 'Hat': 243, 'Headphones': 244, 'Heater': 245, 'Hedgehog': 246, 'Helicopter': 247, 'Helmet': 248, 'High heels': 249, 'Hiking equipment': 250, 'Hippopotamus': 251, 'Home appliance': 252, 'Honeycomb': 253, 'Horizontal bar': 254, 'Horse': 255, 'Hot dog': 256, 'House': 257, 'Houseplant': 258, 'Human arm': 259, 'Beard': 260, 'Human body': 261, 'Human ear': 262, 'Human eye': 263, 'Human face': 264, 'Human foot': 265, 'Human hair': 266, 'Human hand': 267, 'Human head': 268, 'Human leg': 269, 'Human mouth': 270, 'Human nose': 271, 'Humidifier': 272, 'Ice cream': 273, 'Indoor rower': 274, 'Infant bed': 275, 'Insect': 276, 'Invertebrate': 277, 'Ipod': 278, 'Isopod': 279, 'Jacket': 280, 'Jacuzzi': 281, 'Jaguar (Animal)': 282, 'Jeans': 283, 'Jellyfish': 284, 'Jet ski': 285, 'Jug': 286, 'Juice': 287, 'Kangaroo': 288, 'Kettle': 289, 'Kitchen & dining room table': 290, 'Kitchen appliance': 291, 'Kitchen knife': 292, 'Kitchen utensil': 293, 'Kitchenware': 294, 'Kite': 295, 'Knife': 296, 'Koala': 297, 'Ladder': 298, 'Ladle': 299, 'Ladybug': 300, 'Lamp': 301, 'Land vehicle': 302, 'Lantern': 303, 'Laptop': 304, 'Lavender (Plant)': 305, 'Lemon (plant)': 306, 'Leopard': 307, 'Light bulb': 308, 'Light switch': 309, 'Lighthouse': 310, 'Lily': 311, 'Limousine': 312, 'Lion': 313, 'Lipstick': 314, 'Lizard': 315, 'Lobster': 316, 'Loveseat': 317, 'Luggage and bags': 318, 'Lynx': 319, 'Magpie': 320, 'Mammal': 321, 'Man': 322, 'Mango': 323, 'Maple': 324, 'Maracas': 325, 'Marine invertebrates': 326, 'Marine mammal': 327, 'Measuring cup': 328, 'Mechanical fan': 329, 'Medical equipment': 330, 'Microphone': 331, 'Microwave oven': 332, 'Milk': 333, 'Miniskirt': 334, 'Mirror': 335, 'Missile': 336, 'Mixer': 337, 'Mixing bowl': 338, 'Mobile phone': 339, 'Monkey': 340, 'Moths and butterflies': 341, 'Motorcycle': 342, 'Mouse': 343, 'Muffin': 344, 'Mug': 345, 'Mule': 346, 'Mushroom': 347, 'Musical instrument': 348, 'Musical keyboard': 349, 'Nail (Construction)': 350, 'Necklace': 351, 'Nightstand': 352, 'Oboe': 353, 'Office building': 354, 'Office supplies': 355, 'Orange (fruit)': 356, 'Organ (Musical Instrument)': 357, 'Ostrich': 358, 'Otter': 359, 'Oven': 360, 'Owl': 361, 'Oyster': 362, 'Paddle': 363, 'Palm tree': 364, 'Pancake': 365, 'Panda': 366, 'Paper cutter': 367, 'Paper towel': 368, 'Parachute': 369, 'Parking meter': 370, 'Parrot': 371, 'Pasta': 372, 'Pastry': 373, 'Peach': 374, 'Pear': 375, 'Pen': 376, 'Pencil case': 377, 'Pencil sharpener': 378, 'Penguin': 379, 'Perfume': 380, 'Person': 381, 'Personal care': 382, 'Personal flotation device': 383, 'Piano': 384, 'Picnic basket': 385, 'Picture frame': 386, 'Pig': 387, 'Pillow': 388, 'Pineapple': 389, 'Pitcher (Container)': 390, 'Pizza': 391, 'Pizza cutter': 392, 'Plant': 393, 'Plastic bag': 394, 'Plate': 395, 'Platter': 396, 'Plumbing fixture': 397, 'Polar bear': 398, 'Pomegranate': 399, 'Popcorn': 400, 'Porch': 401, 'Porcupine': 402, 'Poster': 403, 'Potato': 404, 'Power plugs and sockets': 405, 'Pressure cooker': 406, 'Pretzel': 407, 'Printer': 408, 'Pumpkin': 409, 'Punching bag': 410, 'Rabbit': 411, 'Raccoon': 412, 'Racket': 413, 'Radish': 414, 'Ratchet (Device)': 415, 'Raven': 416, 'Rays and skates': 417, 'Red panda': 418, 'Refrigerator': 419, 'Remote control': 420, 'Reptile': 421, 'Rhinoceros': 422, 'Rifle': 423, 'Ring binder': 424, 'Rocket': 425, 'Roller skates': 426, 'Rose': 427, 'Rugby ball': 428, 'Ruler': 429, 'Salad': 430, 'Salt and pepper shakers': 431, 'Sandal': 432, 'Sandwich': 433, 'Saucer': 434, 'Saxophone': 435, 'Scale': 436, 'Scarf': 437, 'Scissors': 438, 'Scoreboard': 439, 'Scorpion': 440, 'Screwdriver': 441, 'Sculpture': 442, 'Sea lion': 443, 'Sea turtle': 444, 'Seafood': 445, 'Seahorse': 446, 'Seat belt': 447, 'Segway': 448, 'Serving tray': 449, 'Sewing machine': 450, 'Shark': 451, 'Sheep': 452, 'Shelf': 453, 'Shellfish': 454, 'Shirt': 455, 'Shorts': 456, 'Shotgun': 457, 'Shower': 458, 'Shrimp': 459, 'Sink': 460, 'Skateboard': 461, 'Ski': 462, 'Skirt': 463, 'Skull': 464, 'Skunk': 465, 'Skyscraper': 466, 'Slow cooker': 467, 'Snack': 468, 'Snail': 469, 'Snake': 470, 'Snowboard': 471, 'Snowman': 472, 'Snowmobile': 473, 'Snowplow': 474, 'Soap dispenser': 475, 'Sock': 476, 'Sofa bed': 477, 'Sombrero': 478, 'Sparrow': 479, 'Spatula': 480, 'Spice rack': 481, 'Spider': 482, 'Spoon': 483, 'Sports equipment': 484, 'Sports uniform': 485, 'Squash (Plant)': 486, 'Squid': 487, 'Squirrel': 488, 'Stairs': 489, 'Stapler': 490, 'Starfish': 491, 'Stationary bicycle': 492, 'Stethoscope': 493, 'Stool': 494, 'Stop sign': 495, 'Strawberry': 496, 'Street light': 497, 'Stretcher': 498, 'Studio couch': 499, 'Submarine': 500, 'Submarine sandwich': 501, 'Suit': 502, 'Suitcase': 503, 'Sun hat': 504, 'Sunglasses': 505, 'Surfboard': 506, 'Sushi': 507, 'Swan': 508, 'Swim cap': 509, 'Swimming pool': 510, 'Swimwear': 511, 'Sword': 512, 'Syringe': 513, 'Table': 514, 'Table tennis racket': 515, 'Tablet computer': 516, 'Tableware': 517, 'Taco': 518, 'Tank': 519, 'Tap': 520, 'Tart': 521, 'Taxi': 522, 'Tea': 523, 'Teapot': 524, 'Teddy bear': 525, 'Telephone': 526, 'Television': 527, 'Tennis ball': 528, 'Tennis racket': 529, 'Tent': 530, 'Tiara': 531, 'Tick': 532, 'Tie': 533, 'Tiger': 534, 'Tin can': 535, 'Tire': 536, 'Toaster': 537, 'Toilet': 538, 'Toilet paper': 539, 'Tomato': 540, 'Tool': 541, 'Toothbrush': 542, 'Torch': 543, 'Tortoise': 544, 'Towel': 545, 'Tower': 546, 'Toy': 547, 'Traffic light': 548, 'Traffic sign': 549, 'Train': 550, 'Training bench': 551, 'Treadmill': 552, 'Tree': 553, 'Tree house': 554, 'Tripod': 555, 'Trombone': 556, 'Trousers': 557, 'Truck': 558, 'Trumpet': 559, 'Turkey': 560, 'Turtle': 561, 'Umbrella': 562, 'Unicycle': 563, 'Van': 564, 'Vase': 565, 'Vegetable': 566, 'Vehicle': 567, 'Vehicle registration plate': 568, 'Violin': 569, 'Volleyball (Ball)': 570, 'Waffle': 571, 'Waffle iron': 572, 'Wall clock': 573, 'Wardrobe': 574, 'Washing machine': 575, 'Waste container': 576, 'Watch': 577, 'Watercraft': 578, 'Watermelon': 579, 'Weapon': 580, 'Whale': 581, 'Wheel': 582, 'Wheelchair': 583, 'Whisk': 584, 'Whiteboard': 585, 'Willow': 586, 'Window': 587, 'Window blind': 588, 'Wine': 589, 'Wine glass': 590, 'Wine rack': 591, 'Winter melon': 592, 'Wok': 593, 'Woman': 594, 'Wood-burning stove': 595, 'Woodpecker': 596, 'Worm': 597, 'Wrench': 598, 'Zebra': 599, 'Zucchini': 600}

In [31]:
import pandas as pd
import os

image_filenames_in_dir = os.listdir("open-images-v7/train/images")
label_to_name = pd.read_csv("labeltoName.csv")
labels = pd.read_csv("open-images-v7/train/detections.csv")

# Corrige a extensão sem usar atribuição dentro de lambda
labels["ImageFilename"] = labels["ImageID"].astype(str) + ".jpg"

# Filtra apenas anotações cujas imagens realmente existem na pasta
image_set = set(image_filenames_in_dir)
labels = labels[labels["ImageFilename"].isin(image_set)]

In [32]:
labels = labels.merge(right=label_to_name, left_on='LabelName', right_on="LabelName")
labels[labels["ImageID"]=="00a1d4cc70058bc7"]

,ImageID,Source,LabelName,Confidence,XMin,XMax,YMin,YMax,IsOccluded,IsTruncated,...,XClick1X,XClick2X,XClick3X,XClick4X,XClick1Y,XClick2Y,XClick3Y,XClick4Y,ImageFilename,DisplayName
2350,00a1d4cc70058bc7,activemil,/m/02jvh9,1,0.368668,0.759850,0.585000,0.991875,-1,-1,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,00a1d4cc70058bc7.jpg,Mug
2351,00a1d4cc70058bc7,xclick,/m/0271t,1,0.383677,0.705441,0.747500,0.993750,0,0,...,0.549719,0.383677,0.705441,0.564728,0.747500,0.747500,0.759375,0.993750,00a1d4cc70058bc7.jpg,Drink
2352,00a1d4cc70058bc7,xclick,/m/02_n6y,1,0.263602,0.812383,0.203125,0.365000,1,0,...,0.411820,0.263602,0.696998,0.812383,0.203125,0.256250,0.365000,0.266250,00a1d4cc70058bc7.jpg,Goggles
2353,00a1d4cc70058bc7,xclick,/m/03v5tg,1,0.517824,0.581613,0.451875,0.600625,1,0,...,0.517824,0.566604,0.535647,0.581613,0.455625,0.451875,0.600625,0.600625,00a1d4cc70058bc7.jpg,Drinking straw

In [33]:
labels["LabelIdx"] = labels["DisplayName"].map(label_to_idx)

In [60]:
labels = labels[labels["DisplayName"].isin(classes)]
classes_existentes=labels["DisplayName"].unique()
classes_existentes.sort()
classes_existentes

array(['Beaker', 'Bowl', 'Coffee cup', 'Fork', 'Handbag', 'Kitchen knife', 'Kitchen utensil', 'Knife', 'Measuring cup', 'Mixing bowl', 'Mug', 'Plastic bag', 'Plate', 'Serving tray', 'Spoon', 'Wine glass'], dtype=object)

In [38]:
import yaml
import json
from pathlib import Path

caminho_arquivo_original = 'open-images-v7/dataset.yaml'
caminho_arquivo_modificado = 'open-images-v7/dataset.yaml'

with open(caminho_arquivo_original, 'r', encoding='utf-8') as file:
    dados = yaml.safe_load(file)

    # 4. Filtre a lista 'names' para manter apenas os nomes permitidos
    nomes_originais = dados.get('names', [])
    nomes_filtrados = [nome for nome in nomes_originais if nome in classes_existentes]

    # 5. Atualize os dados com a nova lista de nomes e a nova contagem
    dados['names'] = nomes_filtrados
    dados['nc'] = len(nomes_filtrados)

    # 6. Salve o conteúdo modificado em um novo arquivo YAML
    with open(caminho_arquivo_modificado, 'w', encoding='utf-8') as file:
        # O argumento 'sort_keys=False' mantém a ordem original das chaves
        yaml.dump(dados, file, allow_unicode=True, sort_keys=False)

In [61]:

mapa_nome_para_indice = {}  # Cria um dicionário vazio
for indice, nome in enumerate(classes_existentes):
    mapa_nome_para_indice[nome] = indice

print(mapa_nome_para_indice)

{'Beaker': 0, 'Bowl': 1, 'Coffee cup': 2, 'Fork': 3, 'Handbag': 4, 'Kitchen knife': 5, 'Kitchen utensil': 6, 'Knife': 7, 'Measuring cup': 8, 'Mixing bowl': 9, 'Mug': 10, 'Plastic bag': 11, 'Plate': 12, 'Serving tray': 13, 'Spoon': 14, 'Wine glass': 15}

In [62]:
labels['LabelIdx'] = labels['DisplayName'].map(mapa_nome_para_indice)
labels

,ImageID,Source,LabelName,Confidence,XMin,XMax,YMin,YMax,IsOccluded,IsTruncated,...,XClick2X,XClick3X,XClick4X,XClick1Y,XClick2Y,XClick3Y,XClick4Y,ImageFilename,DisplayName,LabelIdx
3,0000418f7ade0445,xclick,/m/080hkjn,1,0.146667,0.863333,0.133333,0.983333,1,0,...,0.146667,0.863333,0.596667,0.133333,0.690000,0.383333,0.983333,0000418f7ade0445.jpg,Handbag,4
4,0000418f7ade0445,xclick,/m/080hkjn,1,0.173333,0.826667,0.013333,0.820000,0,0,...,0.173333,0.826667,0.703333,0.013333,0.613333,0.453333,0.820000,0000418f7ade0445.jpg,Handbag,4
23,0000608cc97a2b17,xclick,/m/09tvcd,1,0.000000,0.017500,0.566322,0.653810,0,1,...,0.017500,0.002500,0.006250,0.620884,0.611477,0.566322,0.653810,0000608cc97a2b17.jpg,Wine glass,15
24,0000608cc97a2b17,xclick,/m/09tvcd,1,0.090625,0.150000,0.538100,0.701787,1,0,...,0.150000,0.117500,0.118750,0.584196,0.572907,0.538100,0.701787,0000608cc97a2b17.jpg,Wine glass,15
25,0000608cc97a2b17,xclick,/m/09tvcd,1,0.136875,0.186875,0.560677,0.707432,1,0,...,0.186875,0.158750,0.160000,0.630292,0.609595,0.560677,0.707432,0000608cc97a2b17.jpg,Wine glass,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24888,2439836223b8905a,xclick,/m/04kkgm,1,0.554000,0.954000,0.630631,0.996997,1,1,...,0.554000,0.776000,0.954000,0.630631,0.702703,0.996997,0.729730,2439836223b8905a.jpg,Bowl,1
24889,2439836223b8905a,xclick,/m/04kkgm,1,0.636000,0.954000,0.498498,0.693694,1,0,...,0.636000,0.934000,0.954000,0.498498,0.546547,0.693694,0.582583,2439836223b8905a.jpg,Bowl,1
24890,2439836223b8905a,xclick,/m/04kkgm,1,0.682000,0.968000,0.273273,0.528529,1,0,...,0.682000,0.906000,0.968000,0.273273,0.318318,0.528529,0.312312,2439836223b8905a.jpg,Bowl,1
24891,2439836223b8905a,xclick,/m/04kkgm,1,0.684000,0.938000,0.096096,0.288288,1,0,...,0.684000,0.730000,0.938000,0.096096,0.129129,0.288288,0.111111,2439836223b8905a.jpg,Bowl,1
24892,244322430f9ff075,xclick,/m/02p5f1q,1,0.263333,0.661667,0.370927,0.894737,1,0,...,0.491667,0.263333,0.661667,0.370927,0.894737,0.551378,0.456140,244322430f9ff075.jpg,Coffee cup,2

In [64]:
gb = labels.groupby("ImageID")
import os

output_path = "open-images-v7/train/labels"
os.makedirs(output_path, exist_ok=True)
i=0
print("Iniciando o processo de criação dos arquivos de anotação...")
for image_id, group in gb:
    txt_filepath = os.path.join(output_path, f"{image_id}.txt")
    with open(txt_filepath, 'w') as f:
        # Itera sobre cada linha do DataFrame do grupo.
        for _, row in group.iterrows():
            # Formata a linha no formato: LabelIdx XMin XMax YMin YMax.
            # Os valores são separados por tabulação (\t).
            # 'LabelIdx' é convertido para inteiro.
            line = (f"{int(row['LabelIdx'])} {row['XMin']} {row['XMax']} {row['YMin']} {row['YMax']}")
            
            # Escreve a linha formatada no arquivo, seguida por uma quebra de linha.
            f.write(line + '\n')
        i+=1


print(f"Processo concluído! Os arquivos foram salvos em '{output_path}'. {i} imagens")

Iniciando o processo de criação dos arquivos de anotação...
Processo concluído! Os arquivos foram salvos em 'open-images-v7/train/labels'. 4000 imagens

In [1]:
from ultralytics import YOLO
import os

model = YOLO('yolov9m.pt')

# Caminho para o seu arquivo de configuração
data_yaml_path = os.path.abspath('open-images-v7/dataset.yaml')

# Inicia o treinamento com parâmetros ajustados
results = model.train(
    data=data_yaml_path,
    epochs=100,
    imgsz=416,          # Reduzido de 640 para 416
    batch=-1,            # Reduzido drasticamente de 16 para 4
    # Ou use a opção automática (ainda melhor): batch=-1
    name='yoloOpenImg', # Dê um novo nome para não sobrescrever a tentativa anterior
    hsv_h=0.03,      # Hue augmentation
    hsv_s=0.6,       # Saturation augmentation  
    hsv_v=0.5,       # Value augmentation
    translate=0.2,   # Translation augmentation
    scale=0.9,       # Scale augmentation
    fliplr=0.5,      # Horizontal flip
)

New https://pypi.org/project/ultralytics/8.3.214 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.178 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2050, 3902MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=-1, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/pc/Documents/GitHub/HOME/Yolo_trainig/open-images-v7/dataset.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=100, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.03, hsv_s=0.6, hsv_v=0.5, imgsz=416, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov9m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=yoloOpenImg9, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/yoloOpenImg9, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.9, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.2, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=16

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1    171648  ultralytics.nn.modules.block.RepNCSPELAN4    [64, 128, 128, 64, 1]
  3                  -1  1    276960  ultralytics.nn.modules.block.AConv           [128, 240]
  4                  -1  1    629520  ultralytics.nn.modules.block.RepNCSPELAN4    [240, 240, 240, 120, 1]
  5                  -1  1    778320  ultralytics.nn.modules.block.AConv           [240, 360]
  6                  -1  1   1414080  ultralytics.nn.modules.block.RepNCSPELAN4    [360, 360, 360, 180, 1]
  7                  -1  1   1556160  ultralytics.nn.modules.block.AConv           [360, 480]
  8                  -1  1   2511840  ultralytics.nn.modules.block.RepNCSPELAN4    [480, 480, 480, 240, 1]
  9                  -1  1    577440  ultralytics.nn.modules.block.SPPELAN         [480, 480, 240]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1   1586880  ultralytics.nn.modules.block.RepNCSPELAN4    [840, 360, 360, 180, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    715920  ultralytics.nn.modules.block.RepNCSPELAN4    [600, 240, 240, 120, 1]
 16                  -1  1    397808  ultralytics.nn.modules.block.AConv           [240, 184]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1   1480320  ultralytics.nn.modules.block.RepNCSPELAN4    [544, 360, 360, 180, 1]
 19                  -1  1    778080  ultralytics.nn.modules.block.AConv           [360, 240]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   2627040  ultralytics.nn.modules.block.RepNCSPELAN4    [720, 480, 480, 240, 1]
 22        [15, 18, 21]  1   4648384  ultralytics.nn.modules.head.Detect           [16, [240, 360, 480]]
YOLOv9m summary: 348 layers, 20,169,888 parameters, 20,169,872 gradients, 77.6 GFLOPs

Transferred 901/907 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 790.0±241.5 MB/s, size: 380.7 KB)

train: Scanning /home/pc/Documents/GitHub/HOME/Yolo_trainig/open-images-v7/train/labels.cache... 4000 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4000/4000 [00:00<?, ?it/s]
/home/pc/venvs/data_science/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
AutoBatch: Computing optimal batch size for imgsz=416 at 60.0% CUDA memory utilization.
AutoBatch: CUDA:0 (NVIDIA GeForce RTX 2050) 3.81G total, 0.20G reserved, 0.18G allocated, 3.43G free
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
    20169888       32.79         1.143         30.29         254.8        (1, 3, 416, 416)                    list
    20169888       65.58         1.460         34.39         107.6        (2, 3, 416, 416)                    list
    20169888       131.2         1.957         60.31         133.8        (4, 3, 416, 416)                    list
    20169888       262.3         3.001         113.1         186.5        (8, 3, 416, 416)                    list
    20169888       524.6         4.784         218.9         355.7       (16, 3, 416, 416)                    list
AutoBatch: Using batch-size 4 for CUDA:0 2.34G/3.81G (61%) ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 487.5±98.8 MB/s, size: 248.8 KB)

train: Scanning /home/pc/Documents/GitHub/HOME/Yolo_trainig/open-images-v7/train/labels.cache... 4000 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4000/4000 [00:00<?, ?it/s]

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 298.3±96.8 MB/s, size: 149.7 KB)

val: Scanning /home/pc/Documents/GitHub/HOME/Yolo_trainig/open-images-v7/train/labels.cache... 4000 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4000/4000 [00:00<?, ?it/s]

Plotting labels to runs/detect/yoloOpenImg9/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.0005, momentum=0.9) with parameter groups 149 weight(decay=0.0), 156 weight(decay=0.0005), 155 bias(decay=0.0)
Image sizes 416 train, 416 val
Using 8 dataloader workers
Logging results to runs/detect/yoloOpenImg9
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/100      1.25G      2.594      4.043      2.562         30        416: 100%|██████████| 1000/1000 [03:06<00:00,  5.37it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 500/500 [00:49<00:00, 10.11it/s]

                   all       4000       9542      0.634    0.00804    0.00502    0.00149

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/100      1.32G      2.386      3.958      2.467         16        416: 100%|██████████| 1000/1000 [02:55<00:00,  5.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 500/500 [00:50<00:00, 10.00it/s]

                   all       4000       9542    0.00159       0.12    0.00357    0.00102

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/100      1.32G      2.347      4.035      2.433          7        416: 100%|██████████| 1000/1000 [02:54<00:00,  5.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 500/500 [00:49<00:00, 10.06it/s]

                   all       4000       9542    0.00111      0.103    0.00199   0.000549

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/100      1.35G      2.351      4.056      2.419          7        416:  99%|█████████▉| 991/1000 [02:52<00:01,  5.74it/s]

KeyboardInterrupt:

# JUNTANDO OPEN IMAGES COM O MEU

In [ ]:
ds_l = os.listdir("REMY-1/train/labels")
for l in ds_l:
    modificou = False
    old_rows = []
    new_rows = []
    with open(f"{labels_path}/{l}", 'r', encoding='utf-8') as arq:
        for r in arq.readlines():
            old_rows.append(r)

            if (r[0]=='3'):
                modificou=True
                r = '1'+ r[1:]
            elif(r[0]=='4'):
                modificou=True
                r = '5'+ r[1:]

            new_rows.append(r)
    if(modificou):
        with open(f"{labels_path}/{l}", 'w') as arq:
            arq.writelines(new_rows)
        print("antigas")
        for r in old_rows:
            print(r)

        print("novas")
        with open(f"{labels_path}/{l}", 'r', encoding='utf-8') as arq:
            for r in arq.readlines():
                print(r)

# Treinando Com O dataset feito no pelo

removendo sacolas e ecobags

In [12]:
import os

train_path = 'datasetCriado/train'
train_labels_path = os.path.join(train_path, 'labels')

train_labels = os.listdir(train_labels_path)
for label_file in train_labels:
    label_file_path = os.path.join(train_labels_path, label_file)
    with open(label_file_path, 'r') as file:
        lines = file.readlines()
    
    newLines = []
    for line in lines:
        if line.startswith('3'):
            # Replace class '3' with '2' at start of line and keep the rest
            new_line = '2' + line[1:]
            newLines.append(new_line)
        elif line.startswith('5'):
            new_line = '4' + line[1:]
            newLines.append(new_line)
        elif line.startswith('0') or line.startswith('1'):
            newLines.append(line)
        # Skip lines starting with '2' or '4' (delete)
    
    with open(label_file_path, 'w') as file:
        for i, line in enumerate(newLines):
            if i == len(newLines) - 1:
                # Last line - write without newline
                file.write(line.rstrip('\n'))
            else:
                # Other lines - ensure newline
                file.write(line.rstrip('\n') + '\n')

Criando o dataset de validação

In [13]:

import os
import shutil
import random

# Diretórios
train_path = 'datasetCriado/train'
val_path = 'datasetCriado/val'

train_images_path = os.path.join(train_path, 'images')
train_labels_path = os.path.join(train_path, 'labels')
val_images_path = os.path.join(val_path, 'images')
val_labels_path = os.path.join(val_path, 'labels')

# Cria pasta val se não existir
os.makedirs(val_images_path, exist_ok=True)
os.makedirs(val_labels_path, exist_ok=True)

# Lista imagens no train
train_images = [f for f in os.listdir(train_images_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

# Seleciona aleatoriamente 10% das imagens para validação
val_size = int(len(train_images) * 0.1)
val_images = random.sample(train_images, val_size)

# Copia imagens e seus respectivos labels para a pasta val
for image in val_images:
    image_src = os.path.join(train_images_path, image)
    label_name = os.path.splitext(image)[0] + '.txt'
    label_src = os.path.join(train_labels_path, label_name)

    image_dst = os.path.join(val_images_path, image)
    label_dst = os.path.join(val_labels_path, label_name)

    shutil.move(image_src, image_dst)
    if os.path.exists(label_src):
        shutil.move(label_src, label_dst)

# Conta arquivos de label vazios (sem bounding box)
count_empty_labels = 0
for label_file in os.listdir(train_labels_path):
    if not label_file.endswith('.txt'):
        continue
    label_path = os.path.join(train_labels_path, label_file)
    with open(label_path, 'r') as f:
        lines = f.readlines()
        if len(lines) == 0:
            count_empty_labels += 1

print(f'Total de imagens no train: {len(train_images)}')
print(f'Total de imagens para validação: {len(val_images)}')
print(f'Total de labels vazios (sem bounding box): {count_empty_labels}')

Total de imagens no train: 44
Total de imagens para validação: 4
Total de labels vazios (sem bounding box): 12

In [14]:
from ultralytics import YOLO
import os
import torch
torch.cuda.empty_cache() 
model = YOLO('yolov9m.pt')

# Caminho para o seu arquivo de configuração
data_yaml_path = os.path.abspath('datasetCriado/dataset.yaml')

# Inicia o treinamento com parâmetros ajustados
results = model.train(
    data=data_yaml_path,
    epochs=100,
    imgsz=416,
    batch=10,
    lr0=0.001,               # initial learning rate smaller than default
    lrf=0.1,                 # final learning rate multiplier
    name='yoloDatasetCriadoNoPelo',
    hsv_h=0.03,
    hsv_s=0.4,               # lower saturation augmentation
    hsv_v=0.4,               # lower value augmentation
    translate=0.1,           # less translation
    scale=0.9,
    fliplr=0.3,              # lower flip augmentation probability
    patience=20,             # early stopping patience
)

New https://pypi.org/project/ultralytics/8.3.221 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.178 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2050, 3902MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=10, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/dataset.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=100, erasing=0.4, exist_ok=False, fliplr=0.3, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.03, hsv_s=0.4, hsv_v=0.4, imgsz=416, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.001, lrf=0.1, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov9m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=yoloDatasetCriadoNoPelo6, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/yoloDatasetCriadoNoPelo6, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.9, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1    171648  ultralytics.nn.modules.block.RepNCSPELAN4    [64, 128, 128, 64, 1]
  3                  -1  1    276960  ultralytics.nn.modules.block.AConv           [128, 240]
  4                  -1  1    629520  ultralytics.nn.modules.block.RepNCSPELAN4    [240, 240, 240, 120, 1]
  5                  -1  1    778320  ultralytics.nn.modules.block.AConv           [240, 360]
  6                  -1  1   1414080  ultralytics.nn.modules.block.RepNCSPELAN4    [360, 360, 360, 180, 1]
  7                  -1  1   1556160  ultralytics.nn.modules.block.AConv           [360, 480]
  8                  -1  1   2511840  ultralytics.nn.modules.block.RepNCSPELAN4    [480, 480, 480, 240, 1]
  9                  -1  1    577440  ultralytics.nn.modules.block.SPPELAN         [480, 480, 240]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1   1586880  ultralytics.nn.modules.block.RepNCSPELAN4    [840, 360, 360, 180, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    715920  ultralytics.nn.modules.block.RepNCSPELAN4    [600, 240, 240, 120, 1]
 16                  -1  1    397808  ultralytics.nn.modules.block.AConv           [240, 184]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1   1480320  ultralytics.nn.modules.block.RepNCSPELAN4    [544, 360, 360, 180, 1]
 19                  -1  1    778080  ultralytics.nn.modules.block.AConv           [360, 240]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   2627040  ultralytics.nn.modules.block.RepNCSPELAN4    [720, 480, 480, 240, 1]
 22        [15, 18, 21]  1   4639708  ultralytics.nn.modules.head.Detect           [4, [240, 360, 480]]
YOLOv9m summary: 348 layers, 20,161,212 parameters, 20,161,196 gradients, 77.6 GFLOPs

Transferred 901/907 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 6880.2±964.9 MB/s, size: 2838.3 KB)

train: Scanning /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/labels... 40 images, 12 backgrounds, 16 corrupt: 100%|██████████| 40/40 [00:01<00:00, 32.69it/s]

train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/0235c3bc-20250924_164029.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/0b804929-20251028_125843.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/18636ff6-20251028_143446.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/240bb13e-20251028_144036.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/32c81124-20251028_143850.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/330e98f6-20251028_143631.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/3a37fd2c-20251028_143636.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/3bdde441-20251028_125741.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/50d5c3bd-20251028_143553.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/56ae6459-20251028_143545.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/5d0cc231-20251016_101759.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/61cc5ef9-20250924_164637.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/64cdd178-20251023_154819.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/65060680-20251028_143731.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/7cb61fb4-20251028_143632.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/7e872105-20251028_143537.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/8293cab2-20251028_143808.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/876b7933-20251028_125922.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/953eab2e-20251028_144020.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/9a476b32-20251028_143853.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/9ba81f64-20251028_144025.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/a6daf052-20250924_164045.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/a741d603-20251028_125940.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/af9e5f3d-20251028_143824.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/b8e430e0-20251028_143838.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/c6ea9558-20251028_143519.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/ced1567a-20251028_143530.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/d7f52797-20251028_143912.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/d83019fb-20251028_125749.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/d8d84b1c-20251028_143801.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/df1f7672-20251028_144031.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/df54b0f0-20251028_125852.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/e3c59fa3-20251028_143950.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/e4121078-20251028_143604.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/e794a5ef-20251028_143637.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/e8d005e1-20251028_143750.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/ee11ed80-20251028_125920.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/f644bd4b-20251028_143548.jpg: corrupt JPEG restored and saved
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/f7c518d1-20251028_143556.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 4. Possible class labels are 0-3
train: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/images/fcc185eb-20251028_143735.jpg: corrupt JPEG restored and saved
train: New cache created: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3411.0±2807.3 MB/s, size: 3022.8 KB)

val: Scanning /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/val/labels... 4 images, 3 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<00:00,  7.52it/s]

val: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/val/images/ad5b89c2-20251028_125918.jpg: corrupt JPEG restored and saved
val: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/val/images/cb952d17-20251028_130007.jpg: corrupt JPEG restored and saved
val: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/val/images/de1728fc-20250924_164640.jpg: corrupt JPEG restored and saved
val: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/val/images/e414bd3a-20251028_125839.jpg: corrupt JPEG restored and saved
val: New cache created: /home/pc/Documents/GitHub/HOME/Yolo_trainig/datasetCriado/val/labels.cache

Plotting labels to runs/detect/yoloDatasetCriadoNoPelo6/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.001' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.00125, momentum=0.9) with parameter groups 149 weight(decay=0.0), 156 weight(decay=0.00046875), 155 bias(decay=0.0)
Image sizes 416 train, 416 val
Using 8 dataloader workers
Logging results to runs/detect/yoloDatasetCriadoNoPelo6
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/100      3.06G      1.805      5.243      1.519          3        416: 100%|██████████| 3/3 [00:01<00:00,  2.33it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  5.93it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/100      2.66G      1.688      4.982      1.409          3        416: 100%|██████████| 3/3 [00:00<00:00,  3.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 16.24it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/100      2.75G      1.413      3.695      1.492          6        416: 100%|██████████| 3/3 [00:01<00:00,  2.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 17.63it/s]

                   all          4          1    0.00327          1      0.497      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/100      2.84G      1.107      3.291      1.126          7        416: 100%|██████████| 3/3 [00:01<00:00,  2.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.14it/s]

                   all          4          1      0.309          1      0.995      0.796

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/100      2.82G      1.594      6.413      1.251          1        416: 100%|██████████| 3/3 [00:00<00:00,  3.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 17.50it/s]

                   all          4          1    0.00137          1      0.142      0.114

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/100      2.91G      1.497      2.927      1.478          6        416: 100%|██████████| 3/3 [00:01<00:00,  2.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 17.96it/s]

                   all          4          1    0.00148          1     0.0216     0.0151

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/100      2.82G      1.562      2.965      1.341         11        416: 100%|██████████| 3/3 [00:00<00:00,  3.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.13it/s]

                   all          4          1    0.00262          1      0.995      0.697

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/100       2.9G      1.611      3.037      1.493          3        416: 100%|██████████| 3/3 [00:01<00:00,  2.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.54it/s]

                   all          4          1      0.437          1      0.497      0.298

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/100      2.82G      1.312      2.536      1.332         12        416: 100%|██████████| 3/3 [00:00<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 17.25it/s]

                   all          4          1    0.00424          1      0.332      0.166

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/100      2.91G       1.43      2.523      1.352          4        416: 100%|██████████| 3/3 [00:00<00:00,  3.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 16.82it/s]

                   all          4          1    0.00352          1    0.00659    0.00461

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/100       2.9G       1.47      2.147      1.316         11        416: 100%|██████████| 3/3 [00:00<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.65it/s]

                   all          4          1    0.00352          1     0.0035     0.0014

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/100      2.89G      1.222      2.271      1.394          4        416: 100%|██████████| 3/3 [00:00<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.07it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/100       2.9G      1.288      2.071      1.224         17        416: 100%|██████████| 3/3 [00:00<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 17.92it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/100       2.9G      1.176      2.132      1.191          3        416: 100%|██████████| 3/3 [00:00<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.34it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/100       2.9G      1.382      1.948      1.255          5        416: 100%|██████████| 3/3 [00:00<00:00,  3.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.29it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/100       2.9G      1.641      1.987      1.419         10        416: 100%|██████████| 3/3 [00:00<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 17.08it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/100      2.88G      1.412      2.053      1.314          6        416: 100%|██████████| 3/3 [00:00<00:00,  3.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.64it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/100       2.9G      1.551      1.993      1.331          8        416: 100%|██████████| 3/3 [00:00<00:00,  3.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.43it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/100      2.84G      1.345      1.967      1.278         10        416: 100%|██████████| 3/3 [00:00<00:00,  3.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 17.22it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/100       2.9G      1.274      1.549      1.258         10        416: 100%|██████████| 3/3 [00:00<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.59it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/100      2.86G      1.269      1.844      1.248         10        416: 100%|██████████| 3/3 [00:00<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 17.94it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/100       2.9G      1.164      1.962      1.214          5        416: 100%|██████████| 3/3 [00:00<00:00,  3.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 17.93it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/100       2.9G      1.306      1.767       1.32          4        416: 100%|██████████| 3/3 [00:00<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 17.24it/s]

                   all          4          1          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/100       2.9G        1.7      2.233       1.47          6        416: 100%|██████████| 3/3 [00:00<00:00,  3.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.13it/s]

                   all          4          1          0          0          0          0
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 4, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

24 epochs completed in 0.011 hours.
Optimizer stripped from runs/detect/yoloDatasetCriadoNoPelo6/weights/last.pt, 40.8MB
Optimizer stripped from runs/detect/yoloDatasetCriadoNoPelo6/weights/best.pt, 40.8MB

Validating runs/detect/yoloDatasetCriadoNoPelo6/weights/best.pt...
Ultralytics 8.3.178 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2050, 3902MiB)
YOLOv9m summary (fused): 151 layers, 20,015,884 parameters, 0 gradients, 76.5 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 19.67it/s]

                   all          4          1      0.308          1      0.995      0.796
                  copo          1          1      0.308          1      0.995      0.796
Speed: 0.2ms preprocess, 10.4ms inference, 0.0ms loss, 1.3ms postprocess per image
Results saved to runs/detect/yoloDatasetCriadoNoPelo6